Repository LikeKNU/LikeKNU-Web, pull requests merged in 2023-11, with the labels that each got.

#18 fix: vercel 프록시 수정
  like-knu/vercel.json
Labels: ⚙️Chore, 📱FrontEnd

#19 스크롤 페이지 요청 오류 해결
  like-knu/src/pages/InfiniteScrollNoticePage.jsx
  like-knu/src/pages/NotificationPage.jsx
Labels: 🐛Bug, 📱FrontEnd

#24 기기 관련 로직 추가 및 수정
  like-knu/package-lock.json
  like-knu/package.json
  like-knu/public/firebase-messaging-sw.js
  like-knu/src/api/apiUtility.js
  like-knu/src/api/device.js
  like-knu/src/api/deviceRegister.js
  like-knu/src/api/initializer.js
  like-knu/src/api/mainApi.js
  like-knu/src/api/tag.js
  like-knu/src/components/main/DropDown.jsx
  like-knu/src/components/main/MainHeader.jsx
  like-knu/src/components/setting/TagList.jsx
  like-knu/src/components/setting/ToggleSwitch.jsx
  like-knu/src/firebaseCloudMessaging.js
  like-knu/src/index.js
  like-knu/src/pages/SettingNotificationPage.jsx
Labels: 💫Feature, 📱FrontEnd

#26 30분 이내 도착 버스가 없을 경우 없다는 문구 출력
  like-knu/src/components/bus/CityBusListItem.jsx
Labels: 💫Feature, 📱FrontEnd

#30 새로고침 애니메이션 기능 추가
  like-knu/src/components/BusRefreshBtn.jsx
  like-knu/src/components/setting/TagList.jsx
Labels: 💫Feature, 📱FrontEnd

#29 hotfix: 태그 구독 요청 request body 오류 수정
  like-knu/src/components/setting/TagList.jsx
Labels: 📱FrontEnd, 🪓Hotfix

#32 fix: PWA 안드로이드 빌드 설정
  like-knu/public/.well-known/assetlinks.json
  like-knu/public/android/android-launchericon-144-144.png
  like-knu/public/android/android-launchericon-192-192.png
  like-knu/public/android/android-launchericon-48-48.png
  like-knu/public/android/android-launchericon-512-512.png
  like-knu/public/android/android-launchericon-72-72.png
  like-knu/public/android/android-launchericon-96-96.png
  like-knu/public/firebase-messaging-sw.js
  like-knu/public/ios/100.png
  like-knu/public/ios/1024.png
  like-knu/public/ios/114.png
  like-knu/public/ios/120.png
  like-knu/public/ios/128.png
  like-knu/public/ios/144.png
  like-knu/public/ios/152.png
  like-knu/public/ios/16.png
  like-knu/public/ios/167.png
  like-knu/public/ios/180.png
  like-knu/public/ios/192.png
  like-knu/public/ios/20.png
  like-knu/public/ios/256.png
  like-knu/public/ios/29.png
  like-knu/public/ios/32.png
  like-knu/public/ios/40.png
  like-knu/public/ios/50.png
  like-knu/public/ios/512.png
  like-knu/public/ios/57.png
  like-knu/public/ios/58.png
  like-knu/public/ios/60.png
  like-knu/public/ios/64.png
  like-knu/public/ios/72.png
  like-knu/public/ios/76.png
  like-knu/public/ios/80.png
  like-knu/public/ios/87.png
  like-knu/public/manifest.json
Labels: ⚙️Chore, 📱FrontEnd

#36 feat: 공유 기능 추가
  like-knu/public/index.html
  like-knu/src/App.js
  like-knu/src/assets/other_onboarding.png
  like-knu/src/constants/pageName.js
  like-knu/src/pages/SettingTabList.jsx
Labels: 💫Feature, 📱FrontEnd

#38 GA 설정
  like-knu/package-lock.json
  like-knu/package.json
  like-knu/src/App.js
  like-knu/src/RouteChangeTrancker.jsx
Labels: 💫Feature, ⚙️Chore, 📱FrontEnd

#39 메인 공지사항 새 창 열림 + 처음 푸시알림 권한 요청 경험 개선
  like-knu/public/.well-known/assetlinks.json
  like-knu/src/components/main/MainNotice.jsx
  like-knu/src/pages/SettingNotificationPage.jsx
Labels: 🐛Bug, 📱FrontEnd

#40 feat: 푸시 알림 클릭 시 특정 페이지로 이동하도록 설정
  like-knu/public/firebase-messaging-sw.js
  like-knu/src/App.js
  like-knu/src/pages/SettingTabList.jsx
Labels: 💫Feature, 📱FrontEnd

#47 hotfix: 설치 화면 띄우기
  like-knu/src/App.js
Labels: 📱FrontEnd, 🪓Hotfix

#52 푸시알림 허용 메시지
  like-knu/src/firebaseCloudMessaging.js
  like-knu/src/pages/SettingNotificationPage.jsx
Labels: 📱FrontEnd, 🪓Hotfix
